_BASE_: "Base-DiffusionInst.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "/models/swin_base_patch4_window7_224_22k.pkl"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: [ "swin0", "swin1", "swin2", "swin3" ]
  ROI_HEADS:
    NUM_CLASSES: 1203  # LVIS
  DiffusionInst:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1203  # LVIS
    USE_FED_LOSS: True  # LVIS
DATASETS:  # LVIS
  TRAIN: ("lvis_v1_train",)
  TEST: ("lvis_v1_val",)
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
SOLVER:
  IMS_PER_BATCH: 32 #16
  BASE_LR: 0.00005 #0.000025
  STEPS: (105000, 125000) #(210000, 250000)
  MAX_ITER: 135000 #270000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
TEST:  # LVIS
  EVAL_PERIOD: 0  # disable eval during train since long time
