_BASE_: "Base-DiffusionInst.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "/models/torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionInst:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 32 #16
  BASE_LR: 0.00005 #0.000025
  STEPS: (175000, 210000) #(350000, 420000)
  MAX_ITER: 225000 #450000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
